### ISSUE TITLE
7Span: Manuscript Detail page: Change Requests: 9/2/23

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#160]
### Tasks Below (A, B, C, D, E, F, G)
![tasks for adding fields 2](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/8554cb99-0151-441e-8d16-be8420be5f73)
Here is the pdf of the page, so you can zoom in.
[Tasks for adding fields.pdf](https://github.com/PrincetonPEMM/7Span-Phase2/files/12623331/Tasks.for.adding.fields.pdf)

**Comment by WendyLBelcher** [comment]
### Royal_manuscript field
- [ ]  Add sentence depending on this field
- [ ] Place this sentence right after "This date is estimated .." sentence and on the same line
- [ ]  Put the contents of the `royal_manuscript` field in bold

Conditionals
If the `royal_manuscript` field is empty, do nothing
If the `royal_manuscript` field is NOT empty, include this sentence
The Ethiopian king's name that appears in this manuscript is  `royal_manuscript`.

**Comment by WendyLBelcher** [comment]
### Question, ignore for now
`Manuscript `table `Latitude`, `Longitude `fields
Is it possible to use these fields to create a clickable link that takes on to a Google map of that location?

**Comment by WendyLBelcher** [comment]
### MS_location_note
- [ ] Add `MS_location_note` field contents
- [ ] Insert after second sentence, on the same line "This manuscript is held in the repository of ...

Conditionals:
If `MS_location_note` field is empty, do nothing
If `MS_location_note` field is not empty, do the following

**Comment by WendyLBelcher** [comment]
### Manuscript Detail page Table
- [ ] Omit table if no stories [maybe?
Uncatalogued manuscripts have no stories. 
![empty table](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/187e9120-7bcc-4b9d-8d33-0497e67724b1)

**Comment by WendyLBelcher** [comment]
### link_to_digital_copy 
- [ ]  Add sentence depending on this field
- [ ]  Place this sentence right after "This manuscript has x paintings of Marian miracle stories...." and on the same line
- [ ]  Identify PEMM website link to that manuscript's "Paintings by Manuscript" page
- [ ] Put the hyperlink in green (per usual) on the phrase "Paintings by Manuscript."

Conditional
If `link_to_digital_copy` is empty, do nothing
If `link_to_digital_copy` is NOT empty, add this sentence:
To see the paintings in this manuscript, go to its PEMM Paintings by Manuscript page.

**Comment by WendyLBelcher** [comment]
### pemm_volunteer_name
- [ ] If `pemm_volunteer_name` is not empty, display after cataloger sentence like this:

Assistance and/or typing of incipits by `pemm_volunteer_name`.

**Comment by WendyLBelcher** [comment]
### Question, ignore for now
`Manuscript `table `Latitude`, `Longitude `fields
Is it possible to use these fields to create a clickable link that takes on to a Google map of that location?

**Comment by WendyLBelcher** [comment]
### `Manuscript `table `duplicate_missing_scans_rebound_in_disorder`
If `duplicate_missing_scans_rebound_in_disorder` = YES
Display the contents in `mss_rebound_in_disorder_or_breaks_in_sequence` AFTER this sentence
Some manuscripts get rebound in disorder (folios do not appear in the original sequence) or have breaks in the sequence (folios are missing that appeared in the original manuscript). This manuscript is:

**Comment by WendyLBelcher** [comment]
### Do NOT Start, please advise during Standup
`Manuscript` table of stories
- [ ] Omit table if no stories [maybe?
Uncatalogued manuscripts have no stories. 
![empty table](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/187e9120-7bcc-4b9d-8d33-0497e67724b1)

`Manuscript` table `Latitude`, `Longitude `fields
Is it possible to use these fields to create a clickable link that takes on to a Google map of that location?

`Manuscript` table `MS_location_note`
- [ ] Add sentence depending on this field
- [ ] Place this sentence right after the second sentence ("This manuscript is held in the repository of ...) and on the same line
- [ ] Put the contents of the `MS_location_note`  field in bold

Conditionals:
If `MS_location_note` field is empty, do nothing
If `MS_location_note` field is not empty, insert the following sentence
This manuscript's last known location in Ethiopia was in the `MS_location_note`.

**Comment by WendyLBelcher** [comment]
### Do NOT Start, please advise during Standup
### `Manuscript` table of stories
- [ ] Omit table if no stories [maybe?
Uncatalogued manuscripts have no stories. 
![empty table](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/187e9120-7bcc-4b9d-8d33-0497e67724b1)

### `Manuscript` table `Latitude`, `Longitude `fields
Is it possible to use these fields to create a clickable link that takes on to a Google map of that location?

### `Manuscript` table `MS_location_note`
- [ ] Add sentence depending on this field
- [ ] Place this sentence right after the second sentence ("This manuscript is held in the repository of ...) and on the same line
- [ ] Put the contents of the `MS_location_note`  field in bold

Conditionals:
If `MS_location_note` field is empty, do nothing
If `MS_location_note` field is not empty, insert the following sentence
This manuscript's last known location in Ethiopia was in the `MS_location_note`.

**Comment by WendyLBelcher** [comment]
### Do NOT Start, please advise during Standup
### `Manuscript` table of stories
- [ ] Omit table if no stories [maybe?
Uncatalogued manuscripts have no stories. 
![empty table](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/187e9120-7bcc-4b9d-8d33-0497e67724b1)

### `Manuscript` table `Latitude`, `Longitude `fields
Is it possible to use these fields to create a clickable link that takes on to a Google map of that location?

**Comment by WendyLBelcher** [comment]
### Ignore for Now
Change which manuscripts get displayed
Currently, we are only displaying manuscripts with Complete in `manuscript_status`. 
But maybe we should display 
- Incomplete: awaiting digitization 
- Incomplete: not started
- Incomplete: not digitized

Do NOT display 
- Incomplete: irrelevant 
- Duplicate
