### ISSUE TITLE
7Span: Directus: Change fields and add fields

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#191]
### Directus field change in `Collection `table
- [x] Make Directus field `Collections `table field `source `editable (bold, center, link etc.)

Explanation:
We need to have links in this field.
Right now they are spelled out, which looks bad: 
-For more information about the collection, see https://www.bl.uk/collection-guides/ethiopian-collections.
We want to have it look like this
-For more information about the collection, see [link](https://www.bl.uk/collection-guides/ethiopian-collections).

**Comment by WendyLBelcher** [comment]
### Directus add field in `Manuscript` table
- [ ] Add another url link field, titled `manuscript_detail_page_link`
You already added another Directus field, `featured_manuscript_image_link` Add another one exactly like it, and place it right after it in Directus

**Comment by WendyLBelcher** [comment]
### Directus remove field `Our People`?
- [ ] Remove `Our People Title` and `Our People Description` from the website
Or remove it from DirectUs?
![our people](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/611fe050-b08c-412b-803a-451e5958329d)

**Comment by WendyLBelcher** [comment]
### Using the Site (singleton)
- [ ] Add fields in Directus: title, intro, description, note

`Title`: Using the PEMM Website
`Intro`:
Students and scholars can conduct fascinating research using the PEMM website.
`Description`: [with editability, bold, italics, centering, heads]
Interested in African folktales about the Virgin Mary? Go to the Story page to see the titles of almost 1,000 stories. 
Interested in reading stories that have paintings? Click on the filter "With paintings" 
Interested in reading stories written down in the 1300s? Use the slider ...
`Note`

### Contact Us (singleton) 
- [ ] Add fields in Directus: title, intro, description, note

`Title`: Contact PEMM
`Intro`:
You can reach us through the PEMM project email: pemm@princeton.edu
`Description`: [with editability, bold, italics, centering, heads]
Interested in social media? Contact Dawit Muluneh
Interested in paintings? Contact Hanni Makonnen
`Note`

**Comment by WendyLBelcher** [comment]
### Create Events & Workshops Detail Page
Add Fields in Directus: category [either event or workshop, title, date, author, intro, description, note

[Event Post 1]
`Category`: PEMM Workshop
`Title`: Howard University Center for African Studies Summer Institute
`Date`: Friday, August 30, 2024
`Author`: Brenda Randolph, Vanessa , and Dawit Muluneh
`Intro`:
In summer 2024, the Howard University Center for African Studies will host a workshop for public teachers on using PEMM for teaching. 
`Description`:
[several paragraphs]

[Event Post 1]
`Category`: PEMM Event 
`Title`: Lecture on the Miracles of Mary
`Date`: Tuesday, December 10, 2024
`Author`: Wendy Laura Belcher
`Intro`:
Prof. Belcher will deliver a lecture on the findings of the PEMM project about the medieval African folktales about the Virgin Mary.

`Description`:
[several paragraphs]

**Comment by WendyLBelcher** [comment]
Fields in Directus: title, author, intro, description, note

### [Research Post 1]
`Title:`  Miracles of Mary Story Dating
`Author: `PEMM Staff
`Intro:`
PEMM was launched to collect information about the dating of the Ethiopian Miracles of Mary stories. When is the earliest attestation of each tale (in which century does each first appear)? Are some stories more popular in some centuries than others? In which century is each tale the most popular? Do some stories fade in popularity over time? What are the themes of the Ethiopian Marian miracle stories?

`Description:`
PEMM found out that the very earliest stories about the Virgin Mary came into Ethiopia in the fourth century. 

Then, in the 1300s, Ethiopians began to translate Marian miracle stories from Arabic in the late 1300s. It seems that first eight were translated. Then, in 1400, the royal Ethiopian scriptorium produced a manuscript of stories translated from Arabic, totaling 74 translated stories. Stories continued to be translated from Arabic well into the 1400s

Soon, Ethiopians began adding their own stories of miracles the Virgin Mary had performed, many of them in Ethiopia. 
[another few paragraphs]

[Research Post 2]
Title: Miracles of Mary Story Origins
Author: PEMM Staff
Intro: 
Origin: PEMM was launched to collect information about the origin of the Ethiopian Miracles of Mary stories. What is the origin of each Ethiopian Marian miracle tale? Which are indigenous and which are foreign (i.e., told first in Europe or the Middle East)? Do foreign Marian miracle stories fade in popularity over time (i.e., told more often in the 1400s and less often by the 1900s)? Are they more popular in some Ethiopian regions than others? Do foreign and indigenous stories vary by theme (e.g., more foreign stories are about knights)? Do foreign and indigenous stories vary by placement (e.g., foreign stories tend to appear at the beginning of manuscripts)?


### [Research Post 3]
Title: Miracles of Mary Story Themes
Author: PEMM Staff
Intro: 
PEMM was launched to collect information about the themes of the Ethiopian Miracles of Mary stories. Which themes are most common (i.e., appear in the most stories)? Which themes most commonly appear together in a tale (e.g., women and healing)? When and where is the earliest attestation of each theme? Are some themes more popular in one region than another? Do manuscripts have overarching themes (i.e., do some manuscripts have stories mostly on healing, or kingship?)
Description:
[several paragraphs]

### [Research Post 4]
Title: Miracles of Mary Story Characters
Author: PEMM Staff
Intro: PEMM was launched to collect information about the characters in the Ethiopian Miracles of Mary stories. Are men or women protagonists more common? Young or old? Which character professions are most common (e.g., monks or farmers)?
Description:
[several paragraphs]

### [Research Post 5]
Title: Miracles of Mary Story Orders
Author: PEMM Staff
Intro: 
PEMM was launched to collect information about the order in which Ethiopian Miracles of Mary stories appear in manuscripts. Is the order of Miracles of Mary stories within manuscripts random? Is there a standard order of stories (e.g., the same 33 first and in the same order; foreign first, indigenous second; early ones first, later ones second)? Does that order change by century or region? Which stories do most manuscripts begin with? Which stories do most manuscripts end with?
Relationships: Which stories appear most often with which other stories in the same manuscript? Where in manuscripts is each story most likely to appear (e.g., early, middle, late)? Is there a standard collection of stories (e.g., the same 33 told in most manuscripts)? Does the standard change by century or region?
Description:
[several paragraphs]

### [Research Post 6]
Title: Miracles of Mary Story Recensions
Author: PEMM Staff
Intro: PEMM was launched to collect information about the recensions of the Ethiopian Miracles of Mary stories. How did individual Ethiopian Marian miracle stories change over time and region? Did they get longer or shorter?
Description:
[several paragraphs]

### [Research Post 7]
Title: Miracles of Mary Story Provenance
Author: PEMM Staff
Intro: 
PEMM was launched to collect information about the provenance of the Ethiopian Miracles of Mary stories. It is often wrongly said that they were all from Europe. Where is the earliest attestation of each tale (i.e., in which Ethiopian region does each first appear)? Are some stories more popular in some regions than others? In which region is each tale the most popular? The least popular?

Description:
[several paragraphs]

**Comment by WendyLBelcher** [comment]
### Create News & Events Fields in Directus
Create the fields: image_link, category, title, author, intro, description, note

[News Post 1]
[display image_link]
`Category`: PEMM in the News
`Title`: CDH Project Charter: Princeton Ethiopian Miracles of Mary 2019-20
`Author`: Wendy Laura Belcher, Rebecca Sutton Koeser, et al
`Intro`: 
The Princeton University Center for Digital Humanities team of Rebecca Sutton Koeser, Rebecca Munson, Gissoo Doroudian, and Meredith Martin worked with Prof. Belcher in 2019 to lay out the rationale, goals, plan of work, resources needed, terms and conditions, and outcomes of the PEMM Project. It is called CDH Project Charter: Princeton Ethiopian Miracles of Mary 2019-20 and is available through Zenodo.

`Description`:
The PEMM Charter includes the following:
**Part I: Project Overview**
Description and Objectives
Relevant Resources and Projects
Research Questions
Project Significance
Significance for African and Literary Studies
Significance for Digital Humanities
Audiences
Project Team

**Part II: Grant Year 2019-2020 Plans - Data**
Data Status
Types of Data and Storage Format
Past FY19 Data Work
Planned FY20 Data Work
Data Standards and Capture Procedures
Grant Year Objectives – Data
Main Outcomes/Deliverables:
Possibly in Scope – Data:
Out of Scope – Data:
Project Needs – Data
Concerns – Data: Risks
Interdependencies
Data security considerations
Data management plan
Long-term preservation plan
Future Plans
Future Data Work

**Part III: Grant Year Plans - Interface**
Grant Year Objectives – Interface
Main Outcomes/Deliverables:

Part IV: Technical Design Plan
Part V: Deliverable Timeline
Part VI: Grant Year Wrap-up
Part VII: Agreement

Appendix A: Relevant Resources and Projects

To cite this document:

Belcher, Wendy Laura, Rebecca Sutton Koeser, Rebecca Munson, Gissoo Doroudian, and Meredith Martin. CDH Project Charter — Princeton Ethiopian Miracles of Mary 2019-20. Center for Digital Humanities at Princeton. 2019. http://doi.org/10.5281/zenodo.3359178

**Comment by WendyLBelcher** [comment]
### `Paintings `table add field
- [ ] Create new field `painting_sort_order_number`
The field will be an integer field, of up to five digits, no auto-increment. 
You can display the field last in the Directus painting page.
