### ISSUE TITLE
7Span: Manuscript Detail page: C

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#301]

**Comment by WendyLBelcher** [comment]
### Bold on Link
- [ ] Correct link to standard link (green and bold)

![bold on link](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/e6ae60c4-a891-4e63-83e9-37419a28ef8a)

**Comment by WendyLBelcher** [comment]
### Task G: Manuscript table MS_location_note (change request)
Requested wording was:
This manuscript's last known location in Ethiopia was in the MS_location_note.
Change wording to
This manuscript's last known location in Ethiopia: `MS_location_note`.

**Comment by WendyLBelcher** [comment]
### Ignore for Now
Change which manuscripts get displayed
Currently, we are only displaying manuscripts with Complete in `manuscript_status`. 
But maybe we should display 
- Incomplete: awaiting digitization 
- Incomplete: not started
- Incomplete: not digitized

Do NOT display 
- Incomplete: irrelevant 
- Duplicate

**Comment by WendyLBelcher** [comment]
### Bug
- [ ] Omit sentence when no paintings
![paintings sentence](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/7960becb-4179-4e58-ae29-9dc0531478c6)

**Comment by WendyLBelcher** [comment]
### Ignore for Now
Change which manuscripts get displayed
Currently, we are only displaying manuscripts with Complete in `manuscript_status`. 
But maybe we should display 
- Incomplete: awaiting digitization 
- Incomplete: not started
- Incomplete: not digitized

Do NOT display 
- Incomplete: irrelevant 
- Duplicate

`Manuscript` table of stories
- [ ] Omit table if no stories [maybe?
Uncatalogued manuscripts have no stories. 
![empty table](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/187e9120-7bcc-4b9d-8d33-0497e67724b1)

`Manuscript` table `Latitude`, `Longitude `fields
Is it possible to use these fields to create a clickable link that takes on to a Google map of that location?
