### ISSUE TITLE
7Span: Directus: Website Pages to Be Created

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#45]
- [x] Directus Stories, Paintings, Manuscripts completed
- [x] Directus Home page completed
- [x] Directus Research Tools pages Arabic Manuscript, Arabic Stores, Spellings, Repositories, Macomber, Bibliography complete
- [x] Directus About: People is completed

- [ ] Research Tools: `Research & Lessons` (no longer Research Posts page) Index page needs to be done https://github.com/PrincetonPEMM/7Span-Phase2/issues/49: tiles with title and author
- [ ] Research Tools: `Research & Lessons` (no longer Research Posts page) Detail page needs to be created https://github.com/PrincetonPEMM/7Span-Phase2/issues/49 with these fields: Title, Date, Author, Intro, Description, Web_Page_Address, Note

- [ ] Mission: needs to be done: Our Mission https://github.com/PrincetonPEMM/7Span-Phase2/issues/38 and Our History go to the same page, so maybe a singleton with mission title, mission intro, mission description, mission note, and then history title, history intro, history description, history note

- [ ] Connect: `News & Updates Index` page needs to be done https://github.com/PrincetonPEMM/7Span-Phase2/issues/50: tiles with title 
- [ ] Connect: `News & Updates Detail` page needs to be created with these fields https://github.com/PrincetonPEMM/7Span-Phase2/issues/50: Title, Date, Author, Intro, Description, Web_Page_Address, Note
- [ ] 
- [ ] Connect: `Events & Workshops Index` page needs to be done https://github.com/PrincetonPEMM/7Span-Phase2/issues/51: tiles with title
- [ ] Connect: `Events & Workshops Detail` page needs to be created with these fields https://github.com/PrincetonPEMM/7Span-Phase2/issues/51: Title, Date, Author, Intro, Description, Web_Page_Address, Note

- [ ] Connect: `Using the Site` singleton need to be done https://github.com/PrincetonPEMM/7Span-Phase2/issues/52 with title, intro, description, note 
- [ ] Connect: `Contact Us` singleton needs to be done https://github.com/PrincetonPEMM/7Span-Phase2/issues/52 with title, intro, description, note
